name_dics = {
    "1-1 بخش 1 مقدمه به پایتون.pdf": "1-1 Introduction to Python Part 1",
    "10-1 استفاده از async و await در برنامه‌نویسی غیرهمزمان.pdf": "10-1 Using async and await in Asynchronous Programming",
    "10-2 استفاده از منابع همزمان با مدیریت امنیت (با استفاده از asyncio.Lock و asyncio.Semaphore).pdf": "10-2 Using Concurrent Resources with Security Management (using asyncio.Lock and asyncio.Semaphore)",
    "10-3 برنامه‌نویسی غیرهمزمان با asyncio.pdf": "10-3 Asynchronous Programming with asyncio",
    "10-4 زمان‌بندی و مدیریت Taskها در asyncio.pdf": "10-4 Scheduling and Managing Tasks in asyncio",
    "10-5 کار با ورودیخروجی (IO) غیرهمزمان با asyncio": "10-5 Working with Asynchronous I/O using asyncio",
    "10-6 استفاده از Queue‌ها و Synchronization Objects برای مدیریت منابع.pdf": "10-6 Using Queues and Synchronization Objects for Resource Management",
    "10-7 مقایسه عملکرد پردازش‌ها در حالت همزمان و غیرهمزمان.pdf": "10-7 Performance Comparison of Processing in Synchronous and Asynchronous Modes",
    "10-8 استفاده از Multiprocessing برای انجام پردازش‌های موازی.pdf": "10-8 Using Multiprocessing for Parallel Processing",
    "10-9 ایجاد و مدیریت Thread.pdf": "10-9 Creating and Managing Threads",
    "11-1 معرفی pytest و کاربرد آن.pdf": "11-1 Introduction to pytest and Its Applications",
    "11-2 گزارش‌گیری و خروجی‌های تست‌ها در pytest.pdf": "11-2 Reporting and Test Outputs in pytest",
    "11-3 نوشتن و اجرای تست‌ها با pytest.pdf": "11-3 Writing and Running Tests with pytest",
    "11-4 استفاده از Mock و Assert در تست‌ها.pdf": "11-4 Using Mock and Assert in Tests",
    "11-5 بخش 10 تست و دیباگ (Testing & Debugging).pdf": "11-5 Part 10 Testing and Debugging",
    "12-1 Context Managers در پایتون.pdf": "12-1 Context Managers in Python",
    "12-2 Decorators در پایتون.pdf": "12-2 Decorators in Python",
    "12-3 Generators و Iterators در پایتون.pdf": "12-3 Generators and Iterators in Python",
    "12-4 استفاده از asyncio برای برنامه‌نویسی غیرهمزمان.pdf": "12-4 Using asyncio for Asynchronous Programming",
    "12-5 استفاده از multiprocessing و threading در پایتون.pdf": "12-5 Using multiprocessing and threading in Python",
    "12-6 استفاده از الگوریتم‌های مختلف برای حل مسائل پیچیده.pdf": "12-6 Using Different Algorithms to Solve Complex Problems",
    "12-7 استفاده از ساختارهای داده مناسب.pdf": "12-7 Using Appropriate Data Structures",
    "12-8 پروفایلینگ کد در پایتون.pdf": "12-8 Code Profiling in Python",
    "12-9 نوشتن کد بهینه از لحاظ زمان و حافظه.pdf": "12-9 Writing Code Optimized for Time and Memory",
    "12-10 اهمیت نوشتن کد قابل تست.pdf": "12-10 The Importance of Writing Testable Code",
    "12-11 استفاده از try, except, else, finally برای مدیریت استثناها.pdf": "12-11 Using try, except, else, finally for Exception Handling",
    "12-12 ایجاد استثناهای سفارشی در پایتون.pdf": "12-12 Creating Custom Exceptions in Python",
    "2-2 بخش 2 مفاهیم پایه در پایتون.pdf": "2-2 Part 2 Basic Concepts in Python",
    "3-1 تعریف توابع.pdf": "3-1 Defining Functions",
    "3-2 توابع با تعداد متغیر ورودی متغیر (Arbitrary Arguments).pdf": "3-2 Functions with Variable Number of Arguments (Arbitrary Arguments)",
    "3-3 توابع بازگشتی (Recursive Functions).pdf": "3-3 Recursive Functions",
    "3-4 توابع Lambda (توابع ناشناس).pdf": "3-4 Lambda Functions (Anonymous Functions)",
    "3-5 توابع با مقادیر پیش‌فرض (Default Parameters) در پایتون.pdf": "3-5 Functions with Default Parameters in Python",
    "3-6 توابع جامع.pdf": "3-6 Comprehensive Functions",
    "4-1 کار با لیست ها.pdf": "4-1 Working with Lists",
    "4-2 تاپل ها.pdf": "4-2 Tuples",
    "4-3 دیکشنری ها.pdf": "4-3 Dictionaries",
    "4-4 ست ها.pdf": "4-4 Sets",
    "5-1 باز کردن فایل ها.pdf": "5-1 Opening Files",
    "5-2 خواندن فایل ها.pdf": "5-2 Reading Files",
    "5-3 نوشتن فایل ها.pdf": "5-3 Writing Files",
    "6-1 ایجاد استثناهای سفارشی با raise در پایتون.pdf": "6-1 Creating Custom Exceptions with raise in Python",
    "6-2 مدیریت استثناها در پایتون با try, except, else, finally.pdf": "6-2 Exception Handling in Python with try, except, else, finally",
    "6-3 استثناهای رایج در کار با فایل‌ها و نحوه مدیریت آن‌ها.pdf": "6-3 Common File-Related Exceptions and How to Handle Them",
    "6-4 مدیریت فایل‌ها با استفاده از Context Manager (with).pdf": "6-4 File Management Using Context Manager (with)",
    "6-5 مثال‌های کاربردی جامع از کار با فایل‌ها در پایتون.pdf": "6-5 Comprehensive Practical Examples of File Handling in Python",
    "6-6 نکات عملکردی و ایمنی در کار با فایل‌ها.pdf": "6-6 Performance and Security Tips for File Handling",
    "7-1 تعریف کلاس‌ها و ساختار آنها در پایتون.pdf": "7-1 Defining Classes and Their Structure in Python",
    "7-2 مبانی شی‌گرایی (Object-Oriented Programming - OOP) در پایتون.pdf": "7-2 Object-Oriented Programming (OOP) Fundamentals in Python",
    "7-3 ویژگی‌ها و متدهای کلاس‌ها در پایتون.pdf": "7-3 Attributes and Methods of Classes in Python",
    "7-4 متدهای ارثی و بازنویسی متدها (Overriding Methods).pdf": "7-4 Inherited Methods and Method Overriding",
    "7-5 وراثت (Inheritance) در پایتون.pdf": "7-5 Inheritance in Python",
    "7-6 استفاده از پلی‌مورفیسم در پایتون.pdf": "7-6 Using Polymorphism in Python",
    "7-7 پلی‌مورفیسم (Polymorphism).pdf": "7-7 Polymorphism",
    "7-8 انتزاع (Abstraction) در پایتون.pdf": "7-8 Abstraction in Python",
    "7-9 کپسوله‌سازی (Encapsulation).pdf": "7-9 Encapsulation",
    "7-10 دستگاه‌های مدیریت ویژگی‌ها (Property Methods).pdf": "7-10 Property Methods (Attribute Management)",
    "7-11 ترکیب (Composition).pdf": "7-11 Composition",
    "7-12 مدیریت منابع و بستن اشیاء در پایتون.pdf": "7-12 Resource Management and Closing Objects in Python",
    "8-1 کتابخانه datetime - کار با تاریخ و زمان.pdf": "8-1 The datetime Library - Working with Date and Time",
    "8-2 کتابخانه collections.pdf": "8-2 The collections Library",
    "8-3 کتابخانه itertools.pdf": "8-3 The itertools Library",
    "8-4 کتابخانه json.pdf": "8-4 The json Library",
    "8-5 کتابخانه‌های استاندارد و مفید پایتون.pdf": "8-5 Useful Standard Python Libraries",
    "8-6 کتابخانه shutil.pdf": "8-6 The shutil Library",
    "8-7 کتابخانه math و random.pdf": "8-7 The math and random Libraries",
    "9-1 اتصال به پایگاه داده SQL با SQLite در پایتون.pdf": "9-1 Connecting to SQL Database with SQLite in Python",
    "9-2 استفاده از توابع و شرایط SQL در SQLite.pdf": "9-2 Using SQL Functions and Conditions in SQLite",
    "9-3 عملیات CRUD در SQLite با پایتون.pdf": "9-3 CRUD Operations in SQLite with Python",
    "9-4 کار با داده‌های JSON در SQLite.pdf": "9-4 Working with JSON Data in SQLite",
    "9-5 مدیریت تراکنش‌ها (Transactions) در SQLite.pdf": "9-5 Transaction Management in SQLite",
    "9-6 کار با داده‌های JSON در MySQL با پایتون.pdf": "9-6 Working with JSON Data in MySQL with Python",
    "9-7 اتصال به پایگاه داده MySQLPostgreSQL در پایتون.pdf": "9-7 Connecting to MySQL and PostgreSQL Databases in Python",
    "9-8 استفاده از ORM (Object-Relational Mapping) با SQLAlchemy.pdf": "9-8 Using ORM (Object-Relational Mapping) with SQLAlchemy",
    "9-9 انجام عملیات CRUD در MySQL و PostgreSQL (مشابه SQLite).pdf": "9-9 Performing CRUD Operations in MySQL and PostgreSQL (Similar to SQLite)",
    "9-10 مدیریت تراکنش‌ها (Transactions) در MySQL و PostgreSQL.pdf": "9-10 Transaction Management in MySQL and PostgreSQL",
    "9-11 استفاده از زیرپرسش‌ها (Subqueries).pdf": "9-11 Using Subqueries",
    "9-12 گروه‌بندی داده‌ها با GROUP BY.pdf": "9-12 Grouping Data with GROUP BY",
    "9-13 استفاده از JOIN برای ترکیب جداول مختلف.pdf": "9-13 Using JOIN to Combine Different Tables",
    "9-14 مدیریت دسترسی‌ها و مجوزها.pdf": "9-14 Managing Access Rights and Permissions",
}

import os
import re

for filename in os.listdir("."):
    name, ext = os.path.splitext(filename)
    m = re.match(r"(\d+)-(\d+)(.*)", name)
    if m:
        ch = int(m.group(1))
        sec = int(m.group(2))
        rest = m.group(3)
        new_name = f"{ch:02d}-{sec:02d}{rest}{ext}"
        if filename != new_name:
            os.rename(filename, new_name)
            print(f"Renamed: {filename} → {new_name}")